//import해서 간단하게 사용할때
export { ReactComponent as ProfileIcon } from './ProfileIcon.svg'
export { ReactComponent as LogoutIcon } from './LogoutIcon.svg'
export { ReactComponent as ListIcon } from './ListIcon.svg'
export { ReactComponent as GroupIcon } from './GroupIcon.svg'
export { ReactComponent as AddDocsIcon } from './AddDocsIcon.svg'
export { ReactComponent as AddCanvasIcon } from './AddCanvasIcon.svg'
export { ReactComponent as InvitePeopleIcon } from './InvitePeopleIcon.svg'
export { ReactComponent as PlusIcon } from './PlusIcon.svg'
export { ReactComponent as GoogleLogo } from './GoogleLogo.svg'
export { ReactComponent as CloseIcon } from './CloseIcon.svg'
export { ReactComponent as CheckBoxIcon } from './CheckBoxIcon.svg'
export { ReactComponent as ModifyIcon } from './ModifyIcon.svg'