///custom으로 사용하고 싶을떄
export { default as ProfileIconSvg } from './ProfileIcon.svg'
export { default as LogoutIconSvg } from './LogoutIcon.svg'
export { default as ListIconSvg } from './ListIcon.svg'
export { default as GroupIconSvg } from './GroupIcon.svg'
export { default as AddDocsIconSvg } from './AddDocsIcon.svg'
export { default as AddCanvasIconSvg } from './AddCanvasIcon.svg'
export { default as InvitePeopleIconSvg } from './InvitePeopleIcon.svg'
export { default as PlusIcon } from './PlusIcon.svg'
export { default as GoogleLogo } from './GoogleLogo.svg'